# Generated by Django 2.0.6 on 2018-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEngComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Please enter a comment explaining why this form is being rejected.', max_length=2000)),
                ('authortype', models.CharField(blank=True, choices=[('Advisor', 'Advisor'), ('DGS', 'DGS')], help_text='Either DGS or Advisor Commenting', max_length=30)),
            ],
            options={
                'verbose_name': 'MEng Comment',
                'verbose_name_plural': 'MEng Comment',
            },
        ),
        migrations.CreateModel(
            name='MEngPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('coreonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('coretwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('coretwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techtwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techtwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techthreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techthreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('gradtechonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechtwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('gradtechtwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electiveoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electiveonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electivetwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electivetwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electivethreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electivethreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('AdvisorRejected', 'AdvisorRejected'), ('DGSRejected', 'DGSRejected'), ('AdvisorPending', 'AdvisorPending'), ('DGSPending', 'DGSPending'), ('Approved', 'Approved')], default=('New', 'New'), help_text='POS Form State', max_length=20)),
            ],
            options={
                'permissions': (('MEng_Student_View', 'Student View MEng Forms'), ('MEng_Student_Create', 'Student Create MEng Forms'), ('MEng_Advisor_View', 'Advisor View MEng Forms'), ('MEng_DGS_View', 'DGS View MEng Forms'), ('MEng_Admin_View', 'Admin View MEng Forms'), ('MEng_Admin_Create', 'Admin Create MEng Forms')),
                'verbose_name': 'MEng Form',
                'verbose_name_plural': 'MEng Forms',
            },
        ),
    ]
