# Generated by Django 2.0.6 on 2018-08-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEngComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Please enter a comment explaining why this form is being rejected.', max_length=2000)),
                ('authortype', models.CharField(blank=True, choices=[('Advisor', 'Advisor'), ('DGS', 'DGS')], help_text='Either DGS or Advisor Commenting', max_length=30)),
            ],
            options={
                'verbose_name': 'MEng Comment',
                'verbose_name_plural': 'MEng Comment',
            },
        ),
        migrations.CreateModel(
            name='MEngPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('coreonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('coretwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('coretwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techtwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techtwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('techthreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('techthreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('gradtechonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechtwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('gradtechtwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electiveoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electiveonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electivetwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electivetwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electivethreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=20, verbose_name='Term')),
                ('electivethreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('AdvisorRejected', 'AdvisorRejected'), ('DGSRejected', 'DGSRejected'), ('AdvisorPending', 'AdvisorPending'), ('DGSPending', 'DGSPending'), ('Approved', 'Approved')], default=('New', 'New'), help_text='POS Form State', max_length=20)),
                ('concentration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.Concentration')),
                ('coreclassone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mengcoreone', to='shared.Course', verbose_name='Core Industry Prep Course I')),
                ('coreclasstwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mengcoretwo', to='shared.Course', verbose_name='Core Industry Prep Course II')),
                ('electiveone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngelectiveOne', to='shared.Course', verbose_name='Elective I')),
                ('electivethree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngelectiveThree', to='shared.Course', verbose_name='Elective III')),
                ('electivetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngelectiveTwo', to='shared.Course', verbose_name='Elective II')),
                ('gradtechcourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEnggradtechOne', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course I')),
                ('gradtechcoursetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEnggradtechTwo', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course II')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('techcourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngtechONE', to='shared.Course', verbose_name='Concentration Area Course I')),
                ('techcoursethree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngtechThree', to='shared.Course', verbose_name='Concentration Course III')),
                ('techcoursetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MEngtechTWO', to='shared.Course', verbose_name='Concentration Area Course II ')),
            ],
            options={
                'verbose_name': 'MEng Form',
                'verbose_name_plural': 'MEng Forms',
                'permissions': (('MEng_Student_View', 'Student View MEng Forms'), ('MEng_Student_Create', 'Student Create MEng Forms'), ('MEng_Advisor_View', 'Advisor View MEng Forms'), ('MEng_DGS_View', 'DGS View MEng Forms'), ('MEng_Admin_View', 'Admin View MEng Forms'), ('MEng_Admin_Create', 'Admin Create MEng Forms')),
            },
        ),
        migrations.AddField(
            model_name='mengcomment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meng.MEngPOS'),
        ),
    ]
