version: '3'

services:
 db:
   image: postgres
 redis:
   image: "redis:alpine"
 web:
   build: .
   command: python3 manage.py runserver [::]:8000
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db
 celery:
   build: .
   command: celery -A programofstudy worker -l info
   volumes:
     - .:/code
   depends_on:
     - db
     - redis
 celery-beat:
   build: .
   command: celery -A programofstudy beat -l info
   volumes:
     - .:/code
   depends_on:
     - db
     - redis
