version: '3'

services:
 posdb:
   image: postgres
   volumes:
         - posdata-volume:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=${DOCKER_USER}
     - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
     - POSTGRES_DB=${DOCKER_NAME}
 redis:
   image: "redis:alpine"
 posweb-init:
   build: .
   command: /code/initserver.sh
   volumes:
     - .:/code
   depends_on:
     - posdb
 posweb:
   build: .
   command: /code/runserver.sh
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - posweb-init
     - redis
 poscelery:
   build: .
   command: celery -A programofstudy worker -l info
   volumes:
     - .:/code
   depends_on:
     - posdb
     - redis
     - posweb-init
   expose:
     - "8000"
 poscelerybeat:
   build: .
   command: celery -A programofstudy beat -l info --pidfile="/var/run/celery/celerybeat.pid" --schedule="/var/run/celery/celerybeat-schedule"
   volumes:
     - .:/code
   depends_on:
     - posdb
     - redis
     - posweb-init
volumes:
   posdata-volume:
