version: '3'

services:
 db:
   image: postgres
   environment:
     - POSTGRES_USER=${DOCKER_USER}
     - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
     - POSTGRES_DB=${DOCKER_NAME}
 redis:
   image: "redis:alpine"
 web:
   build: .
   command: bash -c "python3 manage.py migrate && python3 manage.py addgroups && python3 manage.py coursetypes && python3 manage.py 590courses && python3 manage.py firstuser && gunicorn programofstudy.wsgi -b [::]:8000"
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db
     - redis
 celery:
   build: .
   command: celery -A programofstudy worker -l info
   volumes:
     - .:/code
   depends_on:
     - db
     - redis
   expose:
     - "8000"
 celerybeat:
   build: .
   command: celery -A programofstudy beat -l info --pidfile="/var/run/celery/celerybeat.pid" --schedule="/var/run/celery/celerybeat-schedule"
   volumes:
     - .:/code
   depends_on:
     - db
     - redis
