# Generated by Django 2.0.6 on 2018-08-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurricularArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a Curricular Area for PhD (e.g. Computer Engineering, Engineering Physics, etc.)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PHDBachelorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Please enter a comment explaining why this form is being rejected.', max_length=2000)),
                ('authortype', models.CharField(blank=True, choices=[('Advisor', 'Advisor'), ('DGS', 'DGS')], help_text='Either DGS or Advisor Commenting', max_length=30)),
            ],
            options={
                'verbose_name': 'PHD Bachelor Comment',
                'verbose_name_plural': 'PHD Bachelor Comments',
            },
        ),
        migrations.CreateModel(
            name='PHDBachelorPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeceoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradeceonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecetwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecetwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecethreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecethreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecefourterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecefourgrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecefiveterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecefivegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecesixterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecesixgrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradtechonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechtwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradtechtwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electiveoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('electiveonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electivetwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('electivetwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('AdvisorRejected', 'AdvisorRejected'), ('DGSRejected', 'DGSRejected'), ('AdvisorPending', 'AdvisorPending'), ('DGSPending', 'DGSPending'), ('Approved', 'Approved')], default=('New', 'New'), help_text='POS Form State', max_length=20)),
                ('curriculararea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PHDBScurricular_area', to='phd.CurricularArea', verbose_name='ECE Curricular Area')),
                ('electiveone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSelectiveOne', to='shared.Course', verbose_name='Elective I')),
                ('electivetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSelectiveTwo', to='shared.Course', verbose_name='Elective II')),
                ('gradececoursefive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEfive', to='shared.Course', verbose_name='Graduate ECE Course V')),
                ('gradececoursefour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEfour', to='shared.Course', verbose_name='Graduate ECE Course IV')),
                ('gradececourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEone', to='shared.Course', verbose_name='Graduate ECE Course I')),
                ('gradececoursesix', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEsix', to='shared.Course', verbose_name='Graduate ECE Course VI')),
                ('gradececoursethree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEthree', to='shared.Course', verbose_name='Graduate ECE Course III')),
                ('gradececoursetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEtwo', to='shared.Course', verbose_name='Graduate ECE Course II')),
                ('gradtechcourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSgradtechOne', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course I')),
                ('gradtechcoursetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSgradtechTwo', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course II')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secondaryadvisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second_Advisor_Bachelor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhD BS Form',
                'verbose_name_plural': 'PhD BS Forms',
                'permissions': (('PHDBS_Student_View', 'Student View PhD BS Forms'), ('PHDBS_Student_Create', 'Student Create PhD BS Forms'), ('PHDBS_Advisor_View', 'Advisor View PhD BS Forms'), ('PHDBS_DGS_View', 'DGS View PhD BS Forms'), ('PHDBS_Admin_View', 'Admin View PhD BS Forms'), ('PHDBS_Admin_Create', 'Admin Create PhD BS Forms')),
            },
        ),
        migrations.CreateModel(
            name='PHDMasterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Please enter a comment explaining why this form is being rejected.', max_length=2000)),
                ('authortype', models.CharField(blank=True, choices=[('Advisor', 'Advisor'), ('DGS', 'DGS')], help_text='Either DGS or Advisor Commenting', max_length=30)),
            ],
            options={
                'verbose_name': 'PHD Master Comment',
                'verbose_name_plural': 'PHD Master Comments',
            },
        ),
        migrations.CreateModel(
            name='PHDMasterPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeceoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradeceonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecetwoterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecetwograde', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradecethreeterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradecethreegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('gradtechoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('gradtechonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('electiveoneterm', models.CharField(choices=[('FALL 2018', 'FALL 2018'), ('SPRING 2018', 'SPRING 2018'), ('FALL 2019', 'FALL 2019'), ('SPRING 2019', 'SPRING 2019'), ('FALL 2020', 'FALL 2020'), ('SPRING 2020', 'SPRING 2020'), ('FALL 2021', 'FALL 2021'), ('SPRING 2021', 'SPRING 2021')], default=('FALL 2018', 'FALL 2018'), max_length=30, verbose_name='Term')),
                ('electiveonegrade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='Grade')),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('New', 'New'), ('AdvisorRejected', 'AdvisorRejected'), ('DGSRejected', 'DGSRejected'), ('AdvisorPending', 'AdvisorPending'), ('DGSPending', 'DGSPending'), ('Approved', 'Approved')], default=('New', 'New'), help_text='POS Form State', max_length=20)),
                ('curriculararea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PHDMScurricular_area', to='phd.CurricularArea', verbose_name='ECE Curricular Area')),
                ('electiveone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSelectiveOne', to='shared.Course', verbose_name='Elective I')),
                ('gradececourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEone', to='shared.Course', verbose_name='Graduate ECE Course I')),
                ('gradececoursethree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEthree', to='shared.Course', verbose_name='Graduate ECE Course III')),
                ('gradececoursetwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEtwo', to='shared.Course', verbose_name='Graduate ECE Course II')),
                ('gradtechcourseone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSgradtechOne', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course I')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secondaryadvisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second_Advisor_Master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhD MS Form',
                'verbose_name_plural': 'PhD MS Forms',
                'permissions': (('PHDMS_Student_View', 'Student View PhD MS Forms'), ('PHDMS_Student_Create', 'Student Create PhD MS Forms'), ('PHDMS_Advisor_View', 'Advisor View PhD MS Forms'), ('PHDMS_DGS_View', 'DGS View PhD MS Forms'), ('PHDMS_Admin_View', 'Admin View PhD MS Forms'), ('PHDMS_Admin_Create', 'Admin Create PhD MS Forms')),
            },
        ),
        migrations.AddField(
            model_name='phdmastercomment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='phd.PHDMasterPOS'),
        ),
        migrations.AddField(
            model_name='phdbachelorcomment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='phd.PHDBachelorPOS'),
        ),
    ]
