# Generated by Django 2.0.6 on 2018-08-31 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdmasterpos',
            name='electiveone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSelectiveOne', to='shared.Course', verbose_name='Elective I'),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='gradececourseone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEone', to='shared.Course', verbose_name='Graduate ECE Course I'),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='gradececoursethree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEthree', to='shared.Course', verbose_name='Graduate ECE Course III'),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='gradececoursetwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSECEtwo', to='shared.Course', verbose_name='Graduate ECE Course II'),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='gradtechcourseone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDMSgradtechOne', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course I'),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phdmasterpos',
            name='secondaryadvisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second_Advisor_Master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phdmastercomment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='phd.PHDMasterPOS'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='curriculararea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PHDBScurricular_area', to='phd.CurricularArea', verbose_name='ECE Curricular Area'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='electiveone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSelectiveOne', to='shared.Course', verbose_name='Elective I'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='electivetwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSelectiveTwo', to='shared.Course', verbose_name='Elective II'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececoursefive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEfive', to='shared.Course', verbose_name='Graduate ECE Course V'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececoursefour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEfour', to='shared.Course', verbose_name='Graduate ECE Course IV'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececourseone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEone', to='shared.Course', verbose_name='Graduate ECE Course I'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececoursesix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEsix', to='shared.Course', verbose_name='Graduate ECE Course VI'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececoursethree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEthree', to='shared.Course', verbose_name='Graduate ECE Course III'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradececoursetwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSECEtwo', to='shared.Course', verbose_name='Graduate ECE Course II'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradtechcourseone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSgradtechOne', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course I'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='gradtechcoursetwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PhDBSgradtechTwo', to='shared.Course', verbose_name='Graduate Technical Elective from ECE or other approved area Course II'),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phdbachelorpos',
            name='secondaryadvisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second_Advisor_Bachelor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phdbachelorcomment',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='phd.PHDBachelorPOS'),
        ),
    ]
